name: Deploy web

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "!apps/web/**/*.stories.tsx"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install dependencies
        run: pnpm install

      - name: Build Web app
        run: pnpm run build --filter web

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: apps/web/dist/client
          log-level: standard
